### ISSUE TITLE
Imports

### ISSUE THREAD

**Issue by SpiderMonkey177** [engineering-11/GPS#3]
May just be my pi, but the code keeps throwing an error on package imports.

**Comment by skuklinsky** [comment]
Did you run "sudo pip3 install adafruit-circuitpython-gps"? And can you send the exact error message so I can debug?

**Comment by SpiderMonkey177** [comment]
It threw in error when I was importing board.  And I ran the sudo pip3

**Comment by skuklinsky** [comment]
Can you copy paste the error message please?

**Comment by SpiderMonkey177** [comment]
I run my pi off my external moniter and cannot ssh into it so I cant actually copy and past the code.  I rememeber saying that it could not import board and quit after that.  It might have just been that my pi could not do it itself.
