### ISSUE TITLE
Searching for Fix

### ISSUE THREAD

**Issue by iantga** [engineering-11/GPS#4]
I found the entire process regarding the set-up. Only issue I came across was when running the code, would receive the message "Searching for fix" continuously (no other data was being printed to the screen).

**Comment by luitelshreejal** [comment]
^I did this with Ian and encountered the same thing.

**Comment by skuklinsky** [comment]
Sometimes it takes a few minutes to acquire a fix. Make sure you do all the optional steps of connecting the extra antennas. For best chances of getting a fix, make sure your antenna has an unobstructed line of sight to the sky. But it should still work indoors if you've connected the antenna and wait a few minutes
